# Generated by Django 2.1.2 on 2018-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0002_auto_20181117_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='М', max_length=2, null=True),
        ),
    ]
