# Generated by Django 2.1.2 on 2018-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_comment',
            field=models.IntegerField(default=0),
        ),
    ]
